---
- name: "Vagrant Virtualbox Setup"
  hosts: localhost
  become: true
  vars:
    vagrant_version: "2.2.14"
    vbox_version: "6.1"
    packer_version: "1.6.5"
    terraform_version: "0.13.5"
    vbox_users:
      - vagrant
      - root
  roles:
    - name: "Install dependencies"
      role: dependencies
    - name: "Install Virtualbox"
      role: virtualbox
    - name: "Install Vagrant"
      role: vagrant
    - name: "Install Packer"
      role: packer
    - name: "Rebuild kernel"
      role: kernel
  tasks:
    - name: "Ensure that Virtualbox is the Vagrant default provider"
      shell: "VAGRANT_DEFAULT_PROVIDER=virtualbox >> ~/.profile && . ~/.profile"
