---
- name: "Rebuild Kernel module on RHEL"
  block:
    - yum:
        name: '*'
        state: latest
    - yum:
        name: "kernel-*"
        state: latest
    - name: "Rebuild Kernel module"
      command: "/usr/lib/virtualbox/vboxdrv.sh setup"
      register: vboxdrv
      ignore_errors: yes
    - name: "Rebooting"
      command: /sbin/reboot
      when: vboxdrv.rc == 1
  when: ansible_os_family == 'RedHat'
- name: "Rebuild Kernel module on Debian"
  block:
    - name: "Rebuild Kernel module"
      command: "/usr/lib/virtualbox/vboxdrv.sh setup"
      register: vboxdrv
      ignore_errors: yes
    - name: "Rebooting"
      command: /sbin/reboot
      when: vboxdrv.rc == 1
  when: ansible_os_family == 'Debian'
